<?= $this->partial('/common/header.phtml', $this) ?>
<form id="form">
    GitHub URL: <input type="text" placeholder="GeoJSON, TopoJSON or CSV URL" id="form-text" class="input-xlarge">
    <button type="submit">Go</button>
</form>
<h3>Example:</h3>
<ol>
</ol>
<script>
$('#form').submit(function(e){
    e.preventDefault();
    var url = $('#form-text').val();
    var matches = url.match('//github\.com/(.*)');
    document.location = '/' + matches[1];
});
</script>
<?= $this->partial('/common/footer.phtml', $this) ?>
