<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title><?= $this->escape($this->data_set->getEAV('title')) ?></title>
<?php if (getenv('GOOGLEANALYTICS_ACCOUNT')) { ?>
<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', <?= json_encode(getenv('GOOGLEANALYTICS_ACCOUNT')) ?>]);
_gaq.push(['_trackPageview']);

(function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
<?php } ?>
<style>
html, body {
  height: 100%;
  margin: 0;
  padding: 0;
}

#map-canvas, #map_canvas {
  height: 100%;
}

@media print {
  html, body {
    height: auto;
  }

  #map-canvas, #map_canvas {
    height: 650px;
  }
}

#area-info {
    width: 300px;
    height: 50%;
    position: absolute;
    top: 50%;
    background: white;
    z-index: 10;
}
#panel {
  position: absolute;
  top: 5px;
  left: 50%;
  margin-left: -180px;
  z-index: 5;
  background-color: #fff;
  padding: 5px;
  border: 1px solid #999;
}
</style>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<script>
var tile_width = 400;
var tile_height = 400;

var wmsTypeOptions = {
    getTileUrl: function(tile, zoom) {
        var projection = map.getProjection();
        var zpow = Math.pow(2, zoom);
        var ul = new google.maps.Point(
            tile.x * tile_width / zpow, 
            (tile.y + 1) * tile_height / zpow
        );
        var lr = new google.maps.Point(
            (tile.x + 1) * tile_width / zpow, 
            tile.y * tile_height / zpow
        );
        var ulw = projection.fromPointToLatLng(ul);
        var lrw = projection.fromPointToLatLng(lr);

        var bbox = ulw.lng() + "," + ulw.lat() + "," + lrw.lng() + "," + lrw.lat();

        var base_url = '';
        <?php if (getenv('IMAGE_PROXY_DOMAIN')) { ?>
        base_url = 'http://' + <?= json_encode(getenv('IMAGE_PROXY_DOMAIN')) ?>;
        <?php } ?>
            base_url += '/wms?Request=GetMap&Layers=' + encodeURIComponent(<?= json_encode($this->data_set->getLayerID()) ?>);
        return base_url += '&BBox=' + bbox + '&Width=' + tile_width + '&height=' + tile_height;
    },
    tileSize: new google.maps.Size(tile_width, tile_height),
    maxZoom: 17,
    minZoom: 0,
    name: 'WMS',
    opacity: 0.6
};

var wmsMapType = new google.maps.ImageMapType(wmsTypeOptions);
var map;

function initialize() {
    var matches = document.location.hash.match('#([0-9.]*),([0-9.]*),([0-9]*)');
    var zoom = 8;
    var lat = 23.9720;
    var lng = 120.9777;
    if (matches) {
        zoom = parseInt(matches[3]);
        lat = parseFloat(matches[1]);
        lng = parseFloat(matches[2]);
    }
    var myLatlng = new google.maps.LatLng(lat, lng);
    var mapOptions = {
        center: myLatlng,
        zoom: zoom,
        streetViewControl: false,
    };

    map = new google.maps.Map(document.getElementById('map-canvas'),
        mapOptions);
    map.overlayMapTypes.insertAt(0, wmsMapType);
    google.maps.event.addListener(map, 'click', function(e){
            $.get('/user/getdatafrompoint/?lat=' + e.latLng.lat() + '&lng=' + e.latLng.lng() + '&layer=' + encodeURIComponent(<?= json_encode($this->data_set->getLayerID()) ?>), function(ret){

            $('#area-info').empty();
            if (ret.error) {
                $('#area-info').text(ret.message);
                return;
            }
            var ul_dom = $('<ul></ul>');
            var li_dom;
            for (var i = 0; i < ret.columns.length; i ++) {
                li_dom = $('<li></li>');
                li_dom.text(ret.columns[i] + ':' + ret.values[i]);
                ul_dom.append(li_dom);
            }
            $('#area-info').html(ul_dom);
        }, 'json');
    });

    google.maps.event.addListener(map, 'zoom_changed', map_change);
    google.maps.event.addListener(map, 'center_changed', map_change);
}

function map_change(){
    document.location.hash = '#' + map.getCenter().lat() + ',' + map.getCenter().lng() + ',' + map.getZoom();
};

google.maps.event.addDomListener(window, 'load', initialize);

</script>
</head>
<body>
<div id="map-canvas"></div>
<div id="area-info">點一下地圖上可以顯示詳細資訊</div>
</body>
</html>
